# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore: # pkg incompatible ESM modules
      - dependency-name: "chalk"
      - dependency-name: "dotenv"
      - dependency-name: "node-fetch"
      - dependency-name: "ora"
